label: Contenido
description: 'Encontrar y administrar contenido.'
display:
  default:
    display_options:
      exposed_form:
        options:
          submit_button: Filtro
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            next: 'Siguiente ›'
            first: '« First'
            last: 'Last »'
      fields:
        title:
          label: Título
        type:
          label: 'Tipo de contenido'
          separator: ', '
        name:
          label: Autor
        status:
          label: Estado
        changed:
          label: Actualizado
        operations:
          label: Operaciones
      filters:
        status:
          expose:
            label: Estado
          group_info:
            label: 'Estado de publicación'
            group_items:
              1:
                title: Publicado
                value: '1'
              2:
                title: 'No publicado'
        type:
          expose:
            label: 'Tipo de contenido'
        title:
          expose:
            label: Título
        langcode:
          expose:
            label: Idioma
      title: Contenido
      empty:
        area_text_custom:
          content: 'No content available.'
    display_title: Máster
  page_1:
    display_options:
      menu:
        title: Contenido
      tab_options:
        title: Contenido
        description: 'Encontrar y administrar contenido'
    display_title: Página
