label: 'Biblioteca de bloques personalizados'
description: 'Encontrar y administrar bloques personalizados.'
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            next: 'Siguiente ›'
          expose:
            items_per_page_label: 'elementos por página'
            items_per_page_options_all_label: '— Todo(s) —'
            offset_label: Desplazamiento
      fields:
        info:
          label: 'Descripción del bloque'
          separator: ', '
        type:
          label: 'Tipo de bloque'
          separator: ', '
        changed:
          label: Actualizado
        operations:
          label: Operaciones
      filters:
        info:
          expose:
            label: 'Descripción del bloque'
        type:
          expose:
            label: 'Tipo de bloque'
      title: 'Biblioteca de bloques personalizados'
      empty:
        area_text_custom:
          content: 'There are no custom blocks available. '
  page_1:
    display_title: Página
    display_options:
      menu:
        title: 'Biblioteca de bloques personalizados'
