label: Archivos
description: 'Encontrar y administrar archivos.'
display:
  default:
    display_title: Máster
    display_options:
      exposed_form:
        options:
          submit_button: Filtro
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          tags:
            next: 'Siguiente ›'
          expose:
            items_per_page_label: 'elementos por página'
            items_per_page_options_all_label: '— Todo(s) —'
            offset_label: Desplazamiento
      fields:
        fid:
          label: Fid
        filename:
          label: Nombre
          separator: ', '
        filemime:
          label: 'MIME type'
        filesize:
          label: Tamaño
        status:
          label: Estado
        created:
          label: 'Fecha de subida'
        changed:
          label: 'Fecha del último cambio'
        count:
          label: 'Usado en'
          format_plural_string: "1 lugar\x03@count lugares"
      filters:
        filename:
          expose:
            label: Filename
        filemime:
          expose:
            label: 'MIME type'
        status:
          expose:
            label: Estado
      title: Archivos
      empty:
        area_text_custom:
          content: 'No files available.'
  page_1:
    display_title: 'Files overview'
    display_options:
      menu:
        title: Archivos
  page_2:
    display_title: 'File usage'
    display_options:
      pager:
        options:
          tags:
            next: 'Siguiente ›'
          expose:
            items_per_page_label: 'elementos por página'
            items_per_page_options_all_label: '— Todo(s) —'
            offset_label: Desplazamiento
      fields:
        entity_label:
          label: Entidad
        type:
          label: 'Tipo de entidad'
        module:
          label: 'Registering module'
        count:
          label: 'Use count'
          format_plural_string: "1\x03@count"
      title: 'File usage'
      arguments:
        fid:
          exception:
            title: Todo
          title: 'File usage information for {{ arguments.fid }}'
