label: Frontpage
description: 'Todo el contenido promovido a la página principal.'
display:
  default:
    display_options:
      empty:
        area_text_custom:
          content: 'Aún no se ha creado contenido para la página principal.'
        title:
          title: 'Welcome to [site:name]'
      exposed_form:
        options:
          submit_button: Apply
          reset_button_label: Reiniciar
          exposed_sorts_label: 'Sort by'
          sort_asc_label: Asc
          sort_desc_label: Desc
      pager:
        options:
          expose:
            items_per_page_label: 'elementos por página'
            items_per_page_options_all_label: '— Todo(s) —'
            offset_label: Desplazamiento
          tags:
            next: 'Siguiente ›'
            first: '« First'
            last: 'Last »'
    display_title: Máster
  feed_1:
    display_title: 'Canal de noticias'
  page_1:
    display_title: Página
